### ISSUE TITLE
Getting TypeError when running in Jupyter Notebook

### ISSUE THREAD

**Issue by BazingaSu** [tensorflow/hub#123]
Had this error message when running example code

using Anaconda Jupyter notebook 
python 3.6
tensorflow ==1.8.0
tensor-hub ==0.1.1

`import tensorflow as tf

import tensorflow_hub as hub

module_url = "https://tfhub.dev/google/universal-sentence-encoder/2"

embed = hub.Module(module_url)`

<img width="1000" alt="screen shot 2018-07-31 at 6 52 11 pm" src="https://user-images.githubusercontent.com/32638336/43455590-f9f04982-94f2-11e8-8fe8-46512a5f739e.png">

this snippet works in console but not in  notebook , any idea ?

**Comment by arnoegw** [comment]
Can't repro. Are you sure you're really running tensorflow>=1.8.0? The _FlagValues class existed in TensorFlow versions up to and including 1.4, but was removed in https://github.com/tensorflow/tensorflow/commit/2652704b576adc16b4d735f651cea1024e88b72e#diff-92ab93112cecf0bbfb502800268d86f7

FWIW, tensorflow_hub=0.1.1 no longer contains a run-time check for the version for tensorflow, like tensorflow 0.1.0 did, because the regex in the original check choked on tensorflow 1.10.0. But tensorflow>=1.8.0 is still required.

**Comment by BazingaSu** [comment]
@arnoegw  Thanks for the reply. it's my bad. my tensorflow was 1.4.0 when I ran this snippet for the first time and got this error. Then I updated tensorflow and reloaded the package but it wasn't actually effective, it was still 1.4.0. 

It works now on tensorflow 1.8.0. 

Thanks. closing issue.
