### ISSUE TITLE
USE - What kind of encoding ?

### ISSUE THREAD

**Issue by truas** [tensorflow/hub#168]
Hello,

USE is trained on sentences to produce its vectors, but it is also capable of encoding words. However, I didn't find in the documentation how it handles "unseen" words, since it also produce vector for "strange" tokens like '#$%!@' . Does it work like character-based methods such as, fastText or ELMo? Or something different?

Regards,
T

**Comment by vbardiovskyg** [comment]
Hi @truas,

there are multiple components at play here. First of all, the module is doing text preprocessing, which could mean that it removes all punctuation before even starting to embed the sentence. Second, it might embed even terms that are not in the vocabulary using OOV buckets. You should be able to confirm this by trying to embed variations of the token you are mentioning.

**Comment by truas** [comment]
Hello @vbardiovskyg ,

Thank you for the explanation, really appreciate it.
These OOV buckets are calculated/inferred using chars or is there a different player in this?

Regards,
T.

**Comment by vbardiovskyg** [comment]
I will use the module https://tfhub.dev/google/nnlm-en-dim128-with-normalization/1 for explanation, because of higher familiarity:

Here, we leave out 2.5% of the vocabulary for the OOV buckets. Let's say we have N buckets. If a word comes in that is not in the vocabulary, it is hashed using some standard function (hash(token)%N) and assigned one of the N buckets.

It is likely that there will be a lot of collisions on unknown tokens, but the hope is that some information is actually preserved and we can use this embedding in the downstream task.

As for USE, I am not actually sure whether and how many OOV buckets it uses. I contacted publishers whether they could document this better, meanwhile closing this issue.

**Comment by truas** [comment]
Thanks again @vbardiovskyg !
In case they get back to you please let us know.

Regards,
T.
