### ISSUE TITLE
Regularization in text modules

### ISSUE THREAD

**Issue by budzianowski** [tensorflow/hub#185]
Regularizations on weights are not visible for me with:
`tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES)`

Running:
```
encoder = hub.Module(.., trainable=True, tags={'train'}))
```
gives back:
`ValueError: No such graph variant: tags=['train']`

Was this tag changed recently?

**Comment by arnoegw** [comment]
Among the `https://tfhub.dev/google/...` modules, only those for image classification / image feature vector extraction have a separate `{"train"}` graph, because their reliance on batch norm necessitates it. None of the text embedding modules so far has needed this train/inference split (either because the graphs are the same, or because they are not fully trainable). Please check the documentation of the modules you want to train about how far they support it.
