### ISSUE TITLE
AmoebaNet: Unsupported collections in graph: ['hub_module_attachments']

### ISSUE THREAD

**Issue by hassanhub** [tensorflow/hub#188]
I'm trying to import the pre-trained AmoebaNet for feature vector extraction, however I encounter this error:

Unsupported collections in graph: ['hub_module_attachments']
Use hub.create_module_spec(..., drop_collections=[...]) as appropriate.

Any idea?
Tensorflow 1.12.0
Tensorflow Hub 0.1.1
CUDA 9.0

**Comment by andresusanopinto** [comment]
Good catch... that module was created using features that only exists on the dev branch :(

If you want to give it a try you can try using the tensorflow_hub/pip_package/build_pip_package.sh to create a tensorflow_hub-0.2dev package from master. Otherwise one has to wait until there is a new release from hub.

**Comment by andresusanopinto** [comment]
Fixed by the release of 0.2.0 back in November.

**Comment by jaytimbadia** [comment]
https://github.com/tensorflow/tensorflow/issues/43190#issue-700580966

Can anyone please look into above mentioned issue?

**Comment by arnoegw** [comment]
@jaytimbadia, that's an entirely different issue. I responded there.
