### ISSUE TITLE
How load other weights in hub.module?

### ISSUE THREAD

**Issue by flomock** [tensorflow/hub#293]
I want to use ELMo in keras and for that i want to use tensorflow-hub, probably similar to (https://github.com/strongio/keras-elmo/blob/master/Elmo%20Keras.ipynb or https://tfhub.dev/google/elmo/2).
My Problem is that I want to use a pre-trained model which does not use words but is trained on proteins (sequences of aminoacids).
I have the torch model weights and I have the tensorflow-hub module. Is there a way to load the pretrained torch model weights into tensorflow-hub module?
Thanks in advance

**Comment by gowtham-kp** [comment]
@flomock A possible way (without any guarantee of success) would be to inspect the hub module to identify which variables you want to change (e.g. with Tensorboard). So you would have to do it for every variable you want to reassign. Most likely this wouldn't make much sense, since the model will behave differently than it did in pytorch.
The recommended way here, would be to create a completely new hub module based on a model in Tensorflow.

**Comment by gowtham-kp** [comment]
@flomock Closing this issue due to the lack of inactivity. Please add additional comments and we can reopen the issue again. Thanks!
