### ISSUE TITLE
Duplicate Tensorflow Log and Tensorflow Hub Log

### ISSUE THREAD

**Issue by nfathoni79** [tensorflow/hub#301]
I imported `tensorflow` and `tensorflow_hub` in my script. I used `tf.logging` and the Tensorflow Hub duplicated the logs like these:
```
INFO:tensorflow:2019-05-14 14:44:38.883379: Step 3999: Train accuracy = 100.0%
I0514 14:44:38.883379 12336 coba_retrain.py:506] 2019-05-14 14:44:38.883379: Step 3999: Train accuracy = 100.0%
INFO:tensorflow:2019-05-14 14:44:38.883379: Step 3999: Cross entropy = 0.002284
I0514 14:44:38.883379 12336 coba_retrain.py:508] 2019-05-14 14:44:38.883379: Step 3999: Cross entropy = 0.002284
INFO:tensorflow:2019-05-14 14:44:39.103342: Step 3999: Validation accuracy = 100.0% (N=100)
I0514 14:44:39.103342 12336 coba_retrain.py:525] 2019-05-14 14:44:39.103342: Step 3999: Validation accuracy = 100.0% (N=100)
```
Is there a way to disable the duplicate logs from Tensorflow Hub?

**Comment by gowtham-kp** [comment]
@nfathoni79 Please go though the [issue](https://github.com/tensorflow/tensorflow/issues/1258) and let me know if that helps. Thanks!

**Comment by nfathoni79** [comment]
@gowtham-kp I think this issue is from Tensorflow Hub.
My script when I didn't import `tensorflow_hub`:
```
import tensorflow as tf

tf.logging.set_verbosity(tf.logging.INFO)
tf.logging.info('This is a log')
```
Results:
```
INFO:tensorflow:This is a log
```
When I imported `tensorflow_hub`:
```
import tensorflow as tf
import tensorflow_hub as hub

tf.logging.set_verbosity(tf.logging.INFO)
tf.logging.info('This is a log')
```
Results:
```
WARNING: Logging before flag parsing goes to stderr.
W0515 10:20:53.158393  6676 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14
INFO:tensorflow:This is a log
I0515 10:20:53.168514  6676 cobalog.py:5] This is a log
```

**Comment by akhorlin** [comment]
I think the issue here is that Tensorflow Hub uses https://abseil.io/docs/python/guides/logging whether as tensorflow uses regular python logging. You can reproduce the same behavior by doing

>>> import tensorflow as tf
>>> tf.logging.set_verbosity(tf.logging.INFO)
>>> tf.logging.info("This is a log")
INFO:tensorflow:This is a log
>>> from absl import logging
>>> tf.logging.info("This is a log")
INFO:tensorflow:This is a log
I0516 13:05:29.684607 140513697215936 <stdin>:1] This is a log

Switching the type of logging used by Tensorflow Hub is something to consider. Meanwhile, the issue could be worked around by re-order the import statements:

import tensorflow_hub as hub
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.INFO)
tf.logging.info('This is a log')

**Comment by nfathoni79** [comment]
@akhorlin Okay, that works by reordering the imports. Thanks.
