### ISSUE TITLE
No module named 'tensorflow_hub' 

### ISSUE THREAD

**Issue by pinnareet** [tensorflow/hub#308]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary): source
TensorFlow version: 1.13.1
Python version: 3.6.4
Installed using virtualenv? pip? conda?: pip3
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
It's on a Google Cloud Platform machine.

Describe the problem
In jupyter-notebook python3
Got the following error
ModuleNotFoundError: No module named 'tensorflow_hub'

When executed import tensorflow_hub as hub

Provide the exact sequence of commands / steps that you executed before running into the problem
Many commands that I can't remember, but basically I installed tensorflow_hub using pip3 install tensorflow-hub

Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

More details at https://github.com/tensorflow/tensorflow/issues/28915

**Comment by rmothukuru** [comment]
I think you have installed Tensorflow Hub in one Environment and you are importing it in another environment.

Because, In the below image, it is shown that the location of TF Hub is in python 3.5 site-packages.
![image](https://user-images.githubusercontent.com/48206667/58546761-ae39ca80-8223-11e9-8be0-8f673c18c7c0.png)

But when you import tensorflow_hub, it is searching for that module in Python 3.6, as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/48206667/58546941-138dbb80-8224-11e9-9736-6d26b522f74f.png)

Can you please recheck and confirm.

**Comment by pinnareet** [comment]
I think that is the problem. What should I do? Thank you!

**Comment by rmothukuru** [comment]
I suspect you have 2 versions of Python installed in your PC. Uninstall one or ensure that there is only one Python Version and that should resolve this issue.

**Comment by rmothukuru** [comment]
@pinnareet ,
Please confirm if your issue is resolved so that we can close it.

**Comment by pinnareet** [comment]
Yes, thanks! Sorry for the delay.
