### ISSUE TITLE
Notebook companion of universal-sentence-encoder does not run

### ISSUE THREAD

**Issue by davidpham87** [tensorflow/hub#31]
In the link provided by the universal sentence encoder module, the notebook seems to be unable to use `hub.Module` correctly. This particular line 
```python
embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/1")
```
yields 

```python
KeyError: "The name 'global_step:0' refers to a Tensor which does not exist. The operation, 'global_step', does not exist in the graph."
```

Actually, the whole graph is not imported. I hope it can help.

**Comment by andresusanopinto** [comment]
Thanks for the report!

We have found the issue.. it relates to "tensorflow 1.8.0rc0" and are working in pushing a fix for the notebooks.

**Comment by andresusanopinto** [comment]
Ok, we have temporarily fixed it by updating the notebooks to install "tensorflow>=1.7" without "--pre" in https://github.com/tensorflow/hub/commit/955b4b9deb867334b3e9a80959791c41eb6bb3bf and https://github.com/tensorflow/hub/commit/75a6fe504b39cc436866b9d613eaa08a09304330.

The real issue is now tracked in #33

**Comment by andresusanopinto** [comment]
Note that your notebook runtime might be "corrupted" due to have "1.8.0rc0" installed.
Please `!pip3 uninstall tensorflow` before re-runing the `!pip install "tensorflow>=1.7"`

**Comment by darshil-babel** [comment]
@pramod2157 You don't need to download it everytime. Once downloaded, it will be stored in /tmp/tfhub_modules folder, which you can reference in your code.

**Comment by Hannabrahman** [comment]
@darshil-babel So would you please tell how and which of the files we need to reference?
My problem is I cannot load the module using server (rather than my pc). It is wierd but I am able to download the module on my own pc, I need to scp that to server and then as you said reference in my code.
Please let me know any suggestions

**Comment by darshil-babel** [comment]
@Hannabrahman No, you don't need to do scp. First run this command 
embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/1")
This will create a binary file (something like this: /tmp/tfhub_modules/c6f5954ffa065cdb2f2e604e740e8838bf21a2d3)
Use that in your code from next time and it will not download again.
embed = hub.Module("/tmp/tfhub_modules/c6f5954ffa065cdb2f2e604e740e8838bf21a2d3")
Note that you also don't need to reinitialise the model again and again.

If you still cannot load the module, then show the logs here.

**Comment by Hannabrahman** [comment]
@darshil-babel thanks.
But as I said my problem is, I am able to use hub.Module() that creates binary file on my local machine. and I don't have problem reusing it nest time.
However, When I try using the same line of code (embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/1")) on a linux server, it takes so long and nothing happen at all. 
That's why I am thinking of accessing the binary file somehow. Or does anyone have problem loading the module to a server?

**Comment by darshil-babel** [comment]
@Hannabrahman If it is taking long time on linux server and nothing is happening, you can print the download progress as stated here: https://github.com/tensorflow/hub/issues/25.

This will give a clue what is happening. Also check the activity monitor while download is in progress.
