### ISSUE TITLE
TensorFlow Hub error when Saving model as H5 or SavedModel

### ISSUE THREAD

**Issue by gogasca** [tensorflow/hub#343]
I want to use this TF Hub asset:
https://tfhub.dev/google/imagenet/resnet_v1_50/feature_vector/3

Versions:
```
Version:  1.15.0-dev20190726
Eager mode:  False
Hub version:  0.5.0
GPU is available
```

Code

```
feature_extractor_url = "https://tfhub.dev/google/imagenet/resnet_v1_50/feature_vector/3"
feature_extractor_layer = hub.KerasLayer(module,
                                         input_shape=(HEIGHT, WIDTH, CHANNELS))
```
I get:
```
ValueError: Importing a SavedModel with tf.saved_model.load requires a 'tags=' argument if there is more than one MetaGraph. Got 'tags=None', but there are 2 MetaGraphs in the SavedModel with tag sets [[], ['train']]. Pass a 'tags=' argument to load this SavedModel.
```
I tried:

```
module = hub.Module("https://tfhub.dev/google/imagenet/resnet_v1_50/feature_vector/3",
                    tags={"train"})
feature_extractor_layer = hub.KerasLayer(module, 
                                         input_shape=(HEIGHT, WIDTH, CHANNELS))
```
But when I try to save the model I get:

```
tf.keras.experimental.export_saved_model(model, tf_model_path)
# model.save(h5_model_path) # Same error 

NotImplementedError: Can only generate a valid config for `hub.KerasLayer(handle, ...)`that uses a string `handle`.
Got `type(handle)`: <class 'tensorflow_hub.module.Module'>
```

Tutorial [here](https://www.tensorflow.org/tutorials/images/hub_with_keras)
[StackoverFlow](https://stackoverflow.com/questions/57229641/tensorflow-hub-error-when-saving-model-as-h5-or-savedmodel)

**Comment by arnoegw** [comment]
Hi @gogasca, thanks for your report. There are two parts in it:

1) The advice in the tutorial is wrong. User should use Hub modules made for TF2 to run the flow in that tutorial, including retraining. We intend to publish a larger selection of those for the release of TF2.

2) hub.KerasLayer cannot save a Keras model config (as required for saving to HDF5) if initialized with a Python callable instead of an object. This is documented at
https://github.com/tensorflow/hub/blob/master/tensorflow_hub/keras_layer.py#L84
You can still save it as a SavedModel, though, which is the default for Keras saving in TF2.
