### ISSUE TITLE
Loading Resnet in tf2

### ISSUE THREAD

**Issue by ArashJavan** [tensorflow/hub#347]
I would like to request the ability to load [Resnet] (https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/3)  modules in TF2 via hub.

Thanks

**Comment by arnoegw** [comment]
Thanks, noted!

Our current plan is slightly different, namely to republish most of tfhub.dev/google/imagenet/... in the new, native TF2 format in time for the TF 2.0 release. This will give you the exact same models (originally from TF-Slim), but avoiding some technicalities about TF1 vs TF2.

**Comment by arnoegw** [comment]
I'm pleased to report that the google/imagenet/... models have received an update to version /4, which changes them from the [hub.Module format for TF1](https://www.tensorflow.org/hub/tf1_hub_module) to the [SavedModel format for TF2](https://www.tensorflow.org/hub/tf2_saved_model).

@ArashJavan, please see https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4

**Comment by ArashJavan** [comment]
@arnoegw 
thanks :)

**Comment by XMK233** [comment]
Hi, @arnoegw . Do you mind telling me how did you do the change from V3 to V4? Thanks. 

I tried this method:
`
import tensorflow_hub as hub
import tensorflow as tf
from pprint import pprint
tf.enable_control_flow_v2()
# tf.disable_control_flow_v2()
layers = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/classification/3",
               trainable=True, arguments=dict(batch_norm_momentum=0.997))
piece_to_share = tf.keras.Model(layers)
# full_model = tf.keras.Sequential([piece_to_share])
tf.saved_model.save(piece_to_share, "mymodel_v4")
`
I don't think I'm correct. Because it seems that the saved model cannot be loaded by `hub.KerasLayer()`.

**Comment by XMK233** [comment]
Hi, @arnoegw . Do you mind telling me how did you do the change from V3 to V4? Thanks.

I tried this method:
`import tensorflow_hub as hub`
`import tensorflow as tf`
`from pprint import pprint`
`tf.enable_control_flow_v2()`

tf.disable_control_flow_v2()
layers = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/classification/3",
trainable=True, arguments=dict(batch_norm_momentum=0.997))
piece_to_share = tf.keras.Model(layers)

full_model = tf.keras.Sequential([piece_to_share])
tf.saved_model.save(piece_to_share, "mymodel_v4")
I don't think I'm correct. Because it seems that the saved model cannot be loaded byhub.KerasLayer()`.

**Comment by XMK233** [comment]
Hi, @arnoegw . Do you mind telling me how did you do the change from V3 to V4? Thanks.

I tried this method:

`import tensorflow_hub as hub
import tensorflow as tf
from pprint import pprint
tf.enable_control_flow_v2()`

tf.disable_control_flow_v2()
layers = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/classification/3",
trainable=True, arguments=dict(batch_norm_momentum=0.997))
piece_to_share = tf.keras.Model(layers)

full_model = tf.keras.Sequential([piece_to_share])
tf.saved_model.save(piece_to_share, "mymodel_v4")
I don't think I'm correct. Because it seems that the saved model cannot be loaded byhub.KerasLayer()`.

**Comment by XMK233** [comment]
Hi, @arnoegw . Do you mind telling me how did you do the change from V3 to V4? Thanks.

I tried this method:

`import tensorflow_hub as hub

import tensorflow as tf

from pprint import pprint

tf.enable_control_flow_v2()`

tf.disable_control_flow_v2()
layers = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/classification/3",
trainable=True, arguments=dict(batch_norm_momentum=0.997))
piece_to_share = tf.keras.Model(layers)

full_model = tf.keras.Sequential([piece_to_share])
tf.saved_model.save(piece_to_share, "mymodel_v4")
I don't think I'm correct. Because it seems that the saved model cannot be loaded byhub.KerasLayer()`.

**Comment by XMK233** [comment]
Hi, @arnoegw . Do you mind telling me how did you do the change from V3 to V4? Thanks.

I tried this method:

`import tensorflow_hub as hub`
`import tensorflow as tf`
`from pprint import pprint`
`tf.enable_control_flow_v2()`

`tf.disable_control_flow_v2()`
`layers = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/classification/3",`
`trainable=True, arguments=dict(batch_norm_momentum=0.997))`
`piece_to_share = tf.keras.Model(layers)`

`full_model = tf.keras.Sequential([piece_to_share])`
`tf.saved_model.save(piece_to_share, "mymodel_v4")`
I don't think I'm correct. Because it seems that the saved model cannot be loaded by `hub.KerasLayer()`.

**Comment by arnoegw** [comment]
https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4 is entiely different from /3: While /3 was written by hub.Module.export(), /4 was written by tf.saved_model.save(); compare [tensorflow.org/hub/tf1_hub_module](https://www.tensorflow.org/hub/tf1_hub_module) vs [tensorflow.org/hub/tf2_saved_model](https://www.tensorflow.org/hub/tf2_saved_model).

Sorry, but the rest of your question seems unrelated.

**Comment by XMK233** [comment]
Thank you :-)

**Comment by binguliki** [comment]
> `import tensorflow_hub as hub` `import tensorflow as tf` `from pprint import pprint` `tf.enable_control_flow_v2()`
> 
> `tf.disable_control_flow_v2()` `layers = hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_50/classification/3",` `trainable=True, arguments=dict(batch_norm_momentum=0.997))` `piece_to_share = tf.keras.Model(layers)`
> 
> `full_model = tf.keras.Sequential([piece_to_share])` `tf.saved_model.save(piece_to_share, "mymodel_v4")`

Hey Bro did U get to know how to load this model that u saved , because i'm working on a project where am facing the same issue
