### ISSUE TITLE
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

### ISSUE THREAD

**Issue by graykode** [tensorflow/hub#350]
```shell
(tfjs) ➜  ~ tensorflowjs_converter \
    --input_format=tf_hub \
    'https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/classification/1' \
./test
Loading the module using TF 1.X interface from /var/folders/63/ffmcnx4933gbk9z_7fllm2zw0000gn/T/tfhub_modules/cc14ad57953629a2bbc0ffe52de5afb5518150b2.
WARNING:tensorflow:From /anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING: Logging before flag parsing goes to stderr.
W0810 00:45:09.462952 4726969792 deprecation.py:323] From /anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-08-10 00:45:12.864207: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-08-10 00:45:12.882761: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
Creating a model with inputs ['images'] and outputs ['module_apply_default/MobilenetV1/Logits/SpatialSqueeze'].
WARNING:tensorflow:From /anaconda3/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:385: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
W0810 00:45:14.082165 4726969792 deprecation.py:323] From /anaconda3/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:385: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From /anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
W0810 00:45:14.082515 4726969792 deprecation.py:323] From /anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "/anaconda3/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 597, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/anaconda3/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 430, in convert_tf_hub_module
    quantization_dtype, skip_op_check, strip_debug_ops)
  File "/anaconda3/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 397, in convert_tf_hub_module_v1
    graph=graph)
  File "/anaconda3/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 140, in optimize_graph
    graph_def=graph_def, graph=graph)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1546, in export_meta_graph
    raise RuntimeError("Exporting/importing meta graphs is not supported when "
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled
```

```
$ pip freeze > log
tb-nightly==1.14.0a20190301
tensorboard==1.14.0
tensorflow==2.0.0a0
tensorflow-estimator==1.14.0
tensorflow-estimator-2.0-preview==1.14.0.dev2019080900
tensorflow-hub==0.5.0
tensorflowjs==1.2.6
termcolor==1.1.0
tf-estimator-nightly==1.14.0.dev2019030115
tf-nightly-2.0-preview==2.0.0.dev20190808
```

When I use tfjs-converter, I had tried in TF 1.14.1, 2.0.0b, a version. but not work.

**Comment by gowthamkpr** [comment]
@graykode Unfortunately you cannot use Hub modules with eager mode at this point of time. We are working on TF2 support, including Eager mode, in time for the TF2.0 release (not preview). SOrry for the inconvenience.

**Comment by graykode** [comment]
@gowthamkpr Is it worked on TF 1.x?..

**Comment by vbardiovskyg** [comment]
Hi Tae-Hwan,

the tfjs converter should support both old hub modules and new SavedModel 2.0.

Please note:
```
tensorflowjs 1.2.6 has requirement tensorflow==1.14.0, but you'll have tensorflow 2.0.0a0 which is incompatible.
```

Still the command you gave works for me at:
```
tensorflow==2.0.0a0
tensorflowjs==1.2.6
tensorflow-hub==0.5.0
```

Can you try a clean install, with something like:
```
pip uninstall tensorflow tensorflow_hub tensorflowjs
pip install tensorflow==2.0.0a0 tensorflow_hub==0.5.0 tensorflowjs==1.2.6
```

**Comment by gowthamkpr** [comment]
@graykode Did you try clean install as recommended by @vbardiovskyg ? Are you still facing the issue?

**Comment by graykode** [comment]
@gowthamkpr No It's working now! I think.. it was some tfjs dependency twist in my Mac.. Thanks for helping I'll close this issue.

**Comment by vishalmhjn** [comment]
tensorflow==2.0.0a0 tensorflow_hub==0.5.0 tensorflowjs==1.2.6: Doesn't work for me. Got the same error

**Comment by vishalmhjn** [comment]
`import tensorflow.compat.v1 as tf
#To make tf 2.0 compatible with tf1.0 code, we disable the tf2.0 functionalities
tf.disable_eager_execution()`

This helps.

**Comment by Navan0** [comment]
@vishalmhjn a small change in the code ,it's changed from `tf.disable_eager_execution()` to  `tf.compat.v1.disable_eager_execution()`

**Comment by windspirit95** [comment]
> `import tensorflow.compat.v1 as tf`
> `#To make tf 2.0 compatible with tf1.0 code, we disable the tf2.0 functionalities`
> `tf.disable_eager_execution()`
> 
> This helps.

It works for me. Thank you.

**Comment by mercertom** [comment]
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()

in all the py files fixed this eager execution meta graphs, variable_scope, and reset graph errors from some old v1 tensorflow code.

**Comment by SincerelyUnique** [comment]
`import tensorflow as tf
import tensorflow_hub as hub
tf.compat.v1.disable_eager_execution()
embed = hub.Module(r"D:\nlp\model")`

it works for me

**Comment by Colorfu1** [comment]
you can also use `tf.compat.v1.disable_v2_behavior()`  to stop all tensorflow2 behaviours.

**Comment by fbaothu** [comment]
> > `import tensorflow.compat.v1 as tf`
> > `#To make tf 2.0 compatible with tf1.0 code, we disable the tf2.0 functionalities`
> > `tf.disable_eager_execution()`
> > This helps.
> 
> It works for me. Thank you.

also works for me!

**Comment by RajKumar077** [comment]
a

**Comment by LogicNg** [comment]
Does it support TF2 now?

**Comment by akhorlin** [comment]
It should if you use a model in TF2 format (the format is shown in tfhub.dev UI). In TF2, the reusable TF hub models are just regular TF SavedModels. The converter should be able to handle them. If there are any issues with the conversion, tensorflowjs repo might be a better place to ask for assistance.

**Comment by santhosh432** [comment]
Works fine with this.

> import tensorflow_hub as hub
> import tensorflow as tf
> tf.compat.v1.disable_eager_execution()

**Comment by NguyenDucTruong2504** [comment]
C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Scripts\python.exe C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\detection.py 
2023-12-28 19:42:48.851071: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\facenett\facenet.py:21: The name tf.disable_eager_execution is deprecated. Please use tf.compat.v1.disable_eager_execution instead.

2023-12-28 19:43:01.407185: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\align\detect_face.py:250: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\util\dispatch.py:1260: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
2023-12-28 19:43:01.548681: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
WARNING:tensorflow:From C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\align\detect_face.py:172: The name tf.nn.xw_plus_b is deprecated. Please use tf.compat.v1.nn.xw_plus_b instead.

Model directory: models
Metagraph file: model-20180402-114759.meta
Checkpoint file: model-20180402-114759.ckpt-275
WARNING:tensorflow:From C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\facenett\facenet.py:384: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.

Traceback (most recent call last):
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\framework\importer.py", line 511, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'gradients/InceptionResnetV1/Bottleneck/BatchNorm/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 512. Shapes are [0] and [512].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\detection.py", line 132, in <module>
    run('models', 'models/facemodel.pkl')
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\detection.py", line 97, in run
    face_recognition = Recognition(model_checkpoint, classifier)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\facenett\face_contrib.py", line 31, in __init__
    self.encoder = Encoder(facenet_model_checkpoint)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\facenett\face_contrib.py", line 71, in __init__
    load_model(facenet_model_checkpoint)
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\facenett\facenet.py", line 384, in load_model
    saver = tf.compat.v1.train.import_meta_graph(os.path.join(model_exp, meta_file), input_map=input_map)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\training\saver.py", line 1583, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\training\saver.py", line 1604, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\framework\meta_graph.py", line 785, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\util\deprecation.py", line 588, in new_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\framework\importer.py", line 407, in import_graph_def
    return _import_graph_def_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Choso\PycharmProjects\AttendanceSystemDemo\venv\Lib\site-packages\tensorflow\python\framework\importer.py", line 516, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'gradients/InceptionResnetV1/Bottleneck/BatchNorm/cond/FusedBatchNorm_1_grad/FusedBatchNormGrad' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 512. Shapes are [0] and [512].
how fix this
