### ISSUE TITLE
AWS Lambda integration

### ISSUE THREAD

**Issue by danielisr** [tensorflow/hub#351]
Trying to run tensorflow hub from the cloud, and I'm running into issues installing from a layer. I'm wondering if there are certain dependencies that aren't pure python, and could that be the reason the kernel AWS uses fails to install it? The error:

Unable to import module 'lambda_function': No module named 'tensorflow_hub'

Any ideas about this problem would be much appreciated.

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture), . Also include your TensorFlow and TF Hub versions. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case.

If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
