### ISSUE TITLE
Issue with reusing module

### ISSUE THREAD

**Issue by zhezhe123** [tensorflow/hub#380]
I was using the universal sentence encoder transformer module for some developments and had no issue before. But when I try to reuse the module today, I got an error, wondering if anyone had similar experience and solution with this?

script: embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder-large/3")

error: variable_scope module_20/ was unused but the corresponding name_scope was already taken.

tf version:2.0.0
hub version:0.6.0

Thanks.

**Comment by rmothukuru** [comment]
@zhezhe123,
I have executed the script provided by you with the same versions of Tensorflow and TF Hub mentioned by you but it worked fine for me. Can you try restarting the kernel or restarting the machine. If the issue still persists, can you please provide more details so that I can reproduce it at my end. Thanks!

**Comment by zhezhe123** [comment]
I restart the machine, now the error message changes to:
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

I could reuse the module on my local machine, above error happened while I was using the virtualenv on our private cloud (it worked last week). Could the issue be on our end? Thanks.

**Comment by gowthamkpr** [comment]
@zhezhe123 Universal sentence encoder (https://tfhub.dev/google/universal-sentence-encoder-large/3) is not available in Tensorflow 2.0. It should only work with Tensorflow 1.x.
