### ISSUE TITLE
Tensorflow hub Saver not created

### ISSUE THREAD

**Issue by rv-ltran** [tensorflow/hub#383]
Hi, I am using the script at the bottom of this link https://github.com/tensorflow/hub/blob/master/docs/common_issues.md#running-inference-on-a-pre-initialized-module

However, I got this message error: "INFO:tensorflow:Saver not created because there are no variables in the graph to restore"

What should I do to make it run?

<img width="1113" alt="Screen Shot 2019-10-11 at 1 41 58 PM" src="https://user-images.githubusercontent.com/49695537/66672712-ebc84e80-ec2c-11e9-8d45-8b6c9843ed35.png">

**Comment by gowthamkpr** [comment]
@rv-ltran Tried to reproduce your error in google colab but was not able to do it. Please find my github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/6b205a06f74ae3003fb54764497d03ae/untitled185.ipynb). 

I have got a warning
`INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Saver not created because there are no variables in the graph to restore`

but you can ignore it safely.

**Comment by gowthamkpr** [comment]
@rv-ltran Any updates from your side?

**Comment by rv-ltran** [comment]
Yes, it works now. Thanks

**Comment by cipri-tom** [comment]
@rv-ltran how did you solve it ?

I am trying to fine-tune a hub model locally and running into this error as well.

**Comment by Petros626** [comment]
@gowthamkpr so can this info ignored for sure? In my case I can't detect objects in the `object_detection_tutorial.ipynb`
