### ISSUE TITLE
Placeholder:0 need the input must be (?,299,299,3)?why

### ISSUE THREAD

**Issue by lykGH** [tensorflow/hub#421]

**Comment by gowthamkpr** [comment]
The problem is that you are feeding the placeholder with a value of different shape. You just have to reshape the input.

Also please go through this [issue](https://stackoverflow.com/questions/40430186/tensorflow-valueerror-cannot-feed-value-of-shape-64-64-3-for-tensor-uplace) for more information. If you are still stuck please post it in stackoverflow as we dont support the support questions here. Thanks!
