### ISSUE TITLE
display_image is missing line of code to show plot

### ISSUE THREAD

**Issue by pete1313** [tensorflow/hub#456]
def display_image(image):
    fig = plt.figure(figsize=(20, 15))
    plt.grid(False)
    plt.imshow(image)
    **plt.show(**)

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your versions of TensorFlow and Hub.

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by pete1313** [comment]
I am sorry my bad.....I forgot to say that I have added line of code and made it bold.......
def display_image(image):
fig = plt.figure(figsize=(20, 15))
plt.grid(False)
plt.imshow(image)
this line of code is missing  **plt.show()**

**Comment by rmothukuru** [comment]
@pete1313,
Your issue is not related to TF Hub. This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-hub) since it is not a bug or feature request. There is also a larger community that reads questions there.
