### ISSUE TITLE
Setting number of features for a ".../feature_vector"-model

### ISSUE THREAD

**Issue by atlesa** [tensorflow/hub#468]
Is it possible to set the "num_features" variable for a TFhub feature_vector-model, so that the size of the output feature vector can be specified?

I see that a typical size for the pre-trained models is 1280.
( https://tfhub.dev/google/imagenet/mobilenet_v2_050_96/feature_vector/4 )

I would like to set it smaller.

**Comment by arnoegw** [comment]
Hi @atlesa, thanks for reaching out.

In short, the answer is: No, one cannot change the size of layers in a SavedModel after the fact.

Some more background:

 1. MobileNets come in different sizes, and their depth multiplier provides coarse-grained control for the number of features in each layer. In MobileNet V1, this has also affected the output layer. In MobileNet V2, the last feature layer has been exempted from this down-scaling, because keeping its full size just adds a small fraction of the cost but helps with fine-grained classification tasks.

 2. If you are determined to enforce a smaller dimension, you can add a dense layer to that effect (likely without non-linearity), and either train its weights for your task, or use fixed random weights as seen in [tf2_semantic_approximate_nearest_neighbors.ipynb](https://github.com/tensorflow/hub/blob/master/examples/colab/tf2_semantic_approximate_nearest_neighbors.ipynb) (search for the section on "Random Projection").

Hope that helps.

**Comment by atlesa** [comment]
Hi @arnoegw.
Thank you for the quick response.
Explanation and suggested workaround are excellent. Thank you much :-)
