### ISSUE TITLE
Running TFHub Elmo example code impossible on Colab

### ISSUE THREAD

**Issue by jeromemassot** [tensorflow/hub#471]
Dear all,

I have just run the Elmo example snippet on Colab and it cannot be run due to the known :
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled.

The Colab instance is in the following state:
TF version: 2.1.0-rc1
Hub version: 0.7.0
Eager mode:  True
GPU is available

Example code snippet

`
elmo = hub.Module("https://tfhub.dev/google/elmo/3", trainable=True)
`

So, could it be possible in the TF-Hub Elmo documentation to include an example for running Elmo from TF-Hub in Colab?

With a remark about the possibility to deactivate the eager execution ?
But not sure that this trick will not cause major issue after ...
tf.compat.v1.disable_eager_execution()

or just encapsulate the call to the Module within:
with tf.Graph().as_default():

I am a newbie in TF and TF-Hub... so there are major risks that my comment is no-sense...
But the documentation should permit to run examples flawlessly in a common Colab notebook.

Thanks a lot

Best regards

Jerome

**Comment by rmothukuru** [comment]
@jeromemassot,
For now only Tensorflow 2.0 modules are loadable via them. In the future many of 1.x Hub modules should be loadable as well.

For the 2.x only modules you can see examples in the notebooks created for the modules [here](https://tfhub.dev/s?q=tf2-preview). 

Since you want to use a Pre-Trained Embedding, you can use one from the above link, instead of Elmo, for `TF Version 2.0`. Thanks!

**Comment by gowthamkpr** [comment]
@jeromemassot ELMO is not available in Tensorflow 2.0 and hence the error. Please use tensorflow 1.x for now 
Its been discussed here in #412 

I am closing this issue as it has been resolved. Thanks!
