### ISSUE TITLE
how to use inception-v3 in real time?

### ISSUE THREAD

**Issue by gpqls** [tensorflow/hub#492]
I want to use inception model to recognize human's face in real time. I will use webcam, but i don't know how to do. Please solve this issue.

**Comment by gowthamkpr** [comment]
@gpqls You can take a look at this [tutorial](https://medium.com/@williamkoehrsen/facial-recognition-using-googles-convolutional-neural-network-5aa752b4240e) to use inception-v3 for facial recognition.

Also please post questions like these on stack overflow as this issue is not related to bug/performance, build/install or feature request related issues. Thanks!
