### ISSUE TITLE
bert_multi_cased_L-12_H-768_A-12 in TF2 SavedModel format

### ISSUE THREAD

**Issue by eduardofv** [tensorflow/hub#493]
It would be great to have bert_multi_cased_L-12_H-768_A-12 in TF2 SavedModel format to use in KerasLayers.

Also, can someone explain why are there BERT models published by Google and by Tensorflow, and how those differ? I've seen that the ones published by Google are in the old format and the ones by Tensorflow are in TF2 format. The BERT Collection has only those published by Google.

**Comment by vbardiovskyg** [comment]
Hi Eduardo, the model has been published here: https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/1.

The two sets of models have a different publisher, because the new one (TF2 SavedModel) comes from the TensorFlow model zoo.

The collection has been also updated and now shows all BERT models: https://tfhub.dev/google/collections/bert/1.

Thanks for the feedback.

**Comment by eduardofv** [comment]
Awesome! Thank you, that will be helpful!
