### ISSUE TITLE
GDAL DRIVER PATH

### ISSUE THREAD

**Issue by ShraddhaPM** [tensorflow/hub#494]
Please help me to resolve this. 
Whenever I open Anaconda Prompt the following new line is appearing from last 2 days only, earlier it was not their. 

The system cannot find the specified path. 
C:\Users\Username>set "GDAL_DRIVER_PATH="
<base>C:\Users\Username>

![kaggle](https://user-images.githubusercontent.com/54763343/73423089-1dd2fd00-4351-11ea-9f9c-bdbf9d1d7d66.JPG)

**Comment by gowthamkpr** [comment]
@ShraddhaPM This issue is not related to Tensorflow Hub, it is related to ananconda itself.

You can refer to the following [link](https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html) to solve the issue. If you cannot, you can post it [here](https://github.com/conda/conda/issues).

I am closing this issue.
