### ISSUE TITLE
Universal Sentence Encoder v2 vs. v4

### ISSUE THREAD

**Issue by rv-ltran** [tensorflow/hub#510]
I am comparing the performance of v2 and v4. I understand that v4's main difference is to upgrade to tensorflow 2.0. However, I can see that v4 performance has been deteriorating comparing to v2. Are there any reasons for that? Or the model is meant to kept this way?
I was using a cosine similarity to identify the most similar terms in 2 lists. V2 yields a much better results than V4. I tested the 2 models on various examples and V2 results is consistently better than V4.

Has there been a research for evaluating the performance of V4?

For example: For the phase "I have a rash on my skin", and run the 2 models on the same list. V2 shows an appropriate results while V4 doesnt. 
- V2 will output the top match as "dermatologist" with cosine similarity = 0.6707976305

- V4 will output the top match as "mental health" cosine similarity = 0.0761242328; and "dermatologist" cosine similarity is very low

**Comment by gowthamkpr** [comment]
@rv-ltran Thanks for reporting, I definitely noticed a significant performance difference between [USE v4](https://colab.sandbox.google.com/gist/gowthamkpr/7338dfa88e6041e066cc1190114f00da/semantic-similarity-with-tf-hub-universal-encoder.ipynb) and [USE v2](https://colab.sandbox.google.com/gist/gowthamkpr/c54cb539b5a4c75562547e051daf9cb8/semantic-similarity-with-tf-hub-universal-encoder.ipynb) for the same input.

**Comment by gowthamkpr** [comment]
We used the sts benchmark and infersent as our primary evaluation set. v4 model is actually better on this task with 0.8 pearsonr on the benchmark dev set, which is a very high number according its leader board.
Please see the colab is here: https://colab.sandbox.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder.ipynb#scrollTo=W-q2r7jyZGb7

For the model performance for your task, I wonder if it is because of the vocab and training corpus coverage. We removed the wikipedia from the training corpus as we found no performance improvement on the eval tasks on SentEval. For your example in particular, "I have a rash on my skin" and "dermatologist" is semantically related but they donot really meant the same thing, neither. It is hard to claim the model perform worse on this example only. Do you have more examples we can examine ?

Also, did you try the large model, and how does that perform ?

**Comment by rv-ltran** [comment]
Yinfei, I see. Maybe the drop of wikipedia dataset impacts my use case performance. I do try it on few other examples, such as: "I have a pain on my knee", V2 would yield a higher cosine similarity of 0.88 for "knee pain", where as V4 will just show "ear nose throat" and cosine similarity with "knee pain" is very low <0.04

I could't be more specific in the use case. Do you have a personal email?

**Comment by rv-ltran** [comment]
Another example is if I compare "knee pain" vs. "knee pain". V2 will yield cosine similarity of 1 for "knee pain" (make sense) , but V4 score is only 0.03

**Comment by vprelovac** [comment]
@rv-ltran can you share an example colab notebook and I can take a look?

**Comment by gowthamkpr** [comment]
@rv-ltran I get the V4 score as 1 when I use USE V4. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/4b65ddbd3989102b21bfbc17e4ddb575/untitled29.ipynb). Thanks!

**Comment by rv-ltran** [comment]
I realized that I was comparing an embedding of V4 with a set list embedding created from a V2 model, which make cosine similarity between "knee pain" and "knee pain" different from 1. --> You are correct. V4 is performing well. My observations is incorrect

**Comment by gowthamkpr** [comment]
Thanks @rv-ltran Can we close this issue as you it is not a prblem anymore?

**Comment by rv-ltran** [comment]
Yes, please close it. Thanks for looking into it
