### ISSUE TITLE
make_image_classifier: write summary/logs for TensorBoard

### ISSUE THREAD

**Issue by debuglevel** [tensorflow/hub#541]
`make_image_classifier` should have an option to write a summary/logs to be visualized by TensorBoard.

/edit:

**System information**
- TensorFlow version (you are using): 2.1, and `tensorflow-hub[make_image_classifier]~=0.6`
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The current version of `make_image_classifier` does not write logs/summaries which can be used to feed TensorBoard.

A command line option like `--summaries_dir /tmp/retrain_logs` should write those after completing the training. For a reference, see [https://github.com/tensorflow/hub/blob/v0.7.0/examples/image_retraining/retrain.py#L1199].

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Probably Tensorflow beginners, for which the `make_image_classifier` seems to be targeted.

**Any Other info.**

**Comment by rmothukuru** [comment]
Can you please confirm if this issue is related to Tensorflow Hub. If so, please include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

If the issue is not related to TF Hub, request to raise an issue in the respective Github Repository. Thanks!

**Comment by rmothukuru** [comment]
If the issue is related to Tensorboard, please raise it in this [Github Repo](https://github.com/tensorflow/tensorboard/issues/new/choose). Thanks!

**Comment by debuglevel** [comment]
Edited the initial comment.

**Comment by arnoegw** [comment]
Thanks, @debuglevel, for the feature request and the pull request https://github.com/tensorflow/hub/pull/551 to implement it. I'll be your reviewer for that and sent some comments.

**Comment by arnoegw** [comment]
Oh, that feature request was addressed a month ago, see issue https://github.com/tensorflow/hub/pull/551#issuecomment-613388047
