### ISSUE TITLE
SciBert in TF Hub

### ISSUE THREAD

**Issue by Saichethan** [tensorflow/hub#598]
How to use SciBert using TF Hub?

**Comment by andresusanopinto** [comment]
Hi @Saichethan, since SciBERT has checkpoints compatible with other TF BERT implementations you could try to use those other implementations to create a TF-Hub model from it.

In particular 
[tf2_encoder_checkpoint_converter.py](https://github.com/tensorflow/models/blob/master/official/nlp/bert/tf2_encoder_checkpoint_converter.py) and [export_tfhub.py](https://github.com/tensorflow/models/blob/master/official/nlp/bert/export_tfhub.py) can be used to convert from a BERT checkpoint into a SavedModel like the one in https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/2

**Comment by mppolak** [comment]
Has anyone had success converting SciBERT to a SavedModel recently? The new export_tfhub.py does not save anything, although I cant seem to locate the error.
