### ISSUE TITLE
Can not get reproducible training of modules

### ISSUE THREAD

**Issue by jdvylder** [tensorflow/hub#60]
Hi

I'm training my own module and that works great, but when I rerun my experiment I get different results. That while I set the tf_random_seed parameter in the RunConfig of the estimator that trains the module. Even if I explicitly set the seed within the module, the training is not reproducible:

```    
   def module_fn(self):
        (seed,_) = tf.get_seed(None)
        tf.set_random_seed(seed)
        ...
```
But I would expect that the default behavior would be to use the seed of the estimator. Any ideas on how to fix this?

Thanks

Jonas

**Comment by arnoegw** [comment]
Thank you, Jonas, for this insightful report.

Indeed, a module_fn  passed to `hub.create_module_spec()` executes in its own tf.Graph whose seed is not set. This may happen outside an Estimator's model_fn, so there is no general way to get hold of the eventual value of RunConfig.tf_random_seed.

Perhaps the best way to do this in general is to call `tf.set_random_seed(seed)` in the module_fn like your workaround suggests, with a seed that is not None? (I suspect you might be getting None in the line  before, from an otherwise untouched Graph.)

**Comment by jdvylder** [comment]
Thanks for the explanation. Any odds that in the future, the estimator class could overwrite the modules graph seed when training start, e.g. when the module exporter is registered to the estimator?

**Comment by arnoegw** [comment]
Module export takes the weights from after training, but the graph(s) of the module are unchanged from when hub.create_module_spec() was called on the module_fn, and that may happen far away from the Estimator that instantiates that module spec into a module eventually. So, no, with the current design, I don't see a better way than calling tf.set_random_seed() in the module_fn.
