### ISSUE TITLE
Universal Sentence Encoder for confidential data

### ISSUE THREAD

**Issue by vcuspinera** [tensorflow/hub#606]
Hi,
I am interested to use USE for text Classification, and I am using this code that gets the embedding as a trainable layer in my ML model:
```
use = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
hub_layer = hub.KerasLayer(use, output_shape=[512], input_shape=[],
                           dtype=tf.string, trainable=True) 
```

I am working with confidential text data, so I am running the model in my computer and this has not been very efficient in terms of timing. However, if instead of having the text as the input of the model I pass the embeddings I would be able to run the model in cloud services (Google Colab or AWS).

So, **I was wondering if it would be valid for the USE model to get the embeddings and after use them as the Input, instead of having the embedding as a trainable layer in the ML model?**

**Comment by arnoegw** [comment]
Hi @vcuspinera , thanks for reaching out!

If I understand correctly, you're not really seeing a bug with the tensorflow_hub library or service, but looking for general how-to advice from the community. For that, [StackOverflow tag tensorflow-hub](https://stackoverflow.com/questions/tagged/tensorflow-hub) might be the better forum. I'm going to close this issue here.

Generally speaking, it is a perfectly valid idea to run a linear classifier (or small neural network) on top of pre-trained but frozen embedding of inputs. As you say, the main risk is that it may deteriorate the end-to-end quality of your model, but you anyways need to evaluate that carefully for any model-building approach, so my main advice would be to go and try. On the plus side, precomputing embeddings once and then using them many times over (in reshuffled order) can greatly accelerate training.

Good luck!
