### ISSUE TITLE
Plan to upgrade ELMO for Tensorflow 2.x

### ISSUE THREAD

**Issue by jaingaurav3** [tensorflow/hub#644]
Dear Team,

Is there any plan to upgrade ELMO package for Tensorflow 2.x?

**Comment by j-grimstad** [comment]
Thank you for your request!

The TensorFlow Hub team does not produce modules ourselves, but we’ll forward your request to potential internal publisher teams. Because we rely on other teams for our assets, we aren’t able to provide public estimates for new module availability, and requests may never be fulfilled.

However, we’ll keep this thread open until it is fulfilled -- we’re tagging this thread as a “Module Request” and adding it to our [Community Module Requests](https://github.com/tensorflow/hub/milestone/1) (we also surface it [in our publishing documentation](https://github.com/tensorflow/hub/tree/master/tfhub_dev#community-requests)). We are accepting [submissions from 3rd party publishers](https://github.com/tensorflow/hub/tree/master/tfhub_dev), so if you or someone from the community is interested in producing and sharing these assets, we’d be happy to publish them.

Please let me know if you have any questions!

**Comment by arghyaganguly** [comment]
An updated version compatible with tensorflow2.x is available on [elmo](https://tfhub.dev/google/elmo/3).Thanks.

**Comment by sara-02** [comment]
@arghyaganguly Does `V3` of elmo support `trainable=true` in tf2. If possible can the minimum sample code be added that works for tf2+elmo in the documentation.
