### ISSUE TITLE
Transfer Learning for Neural Network 

### ISSUE THREAD

**Issue by SachinIchake** [tensorflow/hub#65]
Hi Experts,

I have a model consisting of neural network, LSTM and memory network.  However, It takes almost six hours to complete the training and whenever I want to add new use case's data it needs to retrain for all the data. 

Can we take help of transfer learning to reduce the training time for the new use case data? 
if yes, please guide me.  if no, is there any other way to achieve this. 

Thanks,
Sachin B. Ichake

**Comment by akhorlin** [comment]
Hello Sachin,

It's a bit hard to get a general advice in this case. A lot would depend on
your data and details of the model architecture. Since the issue is not TF
Hub specific, it might be better discussed in a wider forum like
machine-learning, deep-learning tags on stackoverflow. If the model
architectures are the same between training runs, it might be  easy to try
to use the checkpoint from the first training run to initialize the model
for the second training run and see if convergence improves in the second
training run (https://www.tensorflow.org/programmers_guide/saved_model).
