### ISSUE TITLE
import tensorflow_hub ,return ‘No module named 'tensorflow.python.types'

### ISSUE THREAD

**Issue by binxixi** [tensorflow/hub#653]
when tensorflow==2.3.0, 
use jupyter notebook to 'import tensorflow_hub as hub', 
then 'ModuleNotFoundError: No module named 'tensorflow.python.types' back to me.

I checked that this folder exists in the path .
And I try many method to pip tensorflow_hub, it doesn't work.

Need you help, thank a lot.
![`%01GP1R%VFP81$V80DSDJH](https://user-images.githubusercontent.com/65208806/89401570-0f263200-d748-11ea-8207-1d4150de32f3.png)

![(VIH1Z7TS~5{T_FXWH6IQM7](https://user-images.githubusercontent.com/65208806/89401604-1b11f400-d748-11ea-9261-96198e3903d9.png)

![SKCVL8$WE6%AU3$FUMPNX{P](https://user-images.githubusercontent.com/65208806/89401593-15b4a980-d748-11ea-89e5-cfe6a05e7ed5.png)

**Comment by rmothukuru** [comment]
@binxixi,
I could `import` `tensorflow_hub` successfully in the Google Colab. Please find the [Gist](https://colab.research.google.com/gist/rmothukuru/17cc674566f087f6b1f7df00c8955499/hub_653.ipynb). 

You can try restarting the Runtime or Restarting your machine and check if the issue is resolved. Thanks!

**Comment by rmothukuru** [comment]
@binxixi,
Can you please respond to the above comment. Thanks!

**Comment by binxixi** [comment]
> @binxixi，
> 您能否回复上述评论。谢谢！
Version incompatibility。 thanks a lot

**Comment by rmothukuru** [comment]
Sounds good.  Closing the issue. Thanks.
