### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by sofeah98** [tensorflow/hub#667]
Hi. I have run a coding. And I got this error.
AttributeError: 'NoneType' object has no attribute 'keys'
I am new in this. Can someone help me?

**Comment by maringeo** [comment]
Hi @sofeah98 , there might be many reasons why you get this error and it is hard to narrow down the root cause without a minimal code sample that reproduces the error. 

I think asking on stackoverflow.com might be the best place to start. Of course, it's possible that this error is caused by an issue in TF Hub, in which case feel free to reopen this issue.
