### ISSUE TITLE
How to handle large text input when using a tensorflow hub small bert layer?

### ISSUE THREAD

**Issue by abhipn** [tensorflow/hub#728]
I am trying to use this [pre-trained model](https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-768_A-12/1) , for a multi-class classification model.

But the problem is some of my text input sentence have more than 10k words (very large document).

How can I use the pre-trained layer, when the below model only supports 128 input_seq length? I know, my input sentence is getting truncated but how can I fix this and take the entire input.

```
import tensorflow_hub as hub
import tensorflow as tf
import tensorflow_text


text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
x = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")(text_input)
x = hub.KerasLayer("https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-768_A-12/1", trainable=True)(x)
x = tf.keras.layers.Dense(16, activation="softmax")(x["default"])
model = tf.keras.Model(inputs=[text_input], outputs=[x])
model.summary()

model.compile("adam", loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics=["acc"])

model.fit(final_df.comment, final_df.type, batch_size=32)
```

**Comment by arghyaganguly** [comment]
@abhipn , could you please try this snippet 

preprocessor = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
tokenizer = hub.KerasLayer(preprocessor(text_input))
tokenized_inputs = [tokenize(segment) for segment in text_inputs]
seq_length = #max length of your sentence             #your choice here
bert_pack_inputs = hub.KerasLayer(preprocessor.bert_pack_inputs, arguments=dict(seq_length=seq_length))
encoder_inputs = bert_pack_inputs(tokenized_inputs)
encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-768_A-12/1", trainable=True)
outputs = encoder(encoder_inputs)

#pooled_output = outputs["pooled_output"] # [batch_size, 768].
#sequence_output = outputs["sequence_output"] # [batch_size, seq_length, 768].

#The encoder's outputs are the pooled_output to represents each input sequence as a whole,
#and the sequence_output to represent each input token in context.

instead of 
x = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")(text_input)
x = hub.KerasLayer("https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-768_A-12/1", trainable=True)(x)

and try proceeding from there.

**Comment by abhipn** [comment]
@arghyaganguly Can you add an example on how it works?

Lets says I have a document as a sentence with 5000 words? 
Will it split the sentence into `sentences of 128 word` and process it and then concat all the outputs from encoder to get final output?

Will this work in batches?

**Comment by arghyaganguly** [comment]
@abhipn , for more information you can check  in the "General usage section" from :-
https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3

**Comment by rmothukuru** [comment]
@abhipn,
Can you please respond to the above comment. Thanks!
