### ISSUE TITLE
hub.load creates WARNING:tensorflow:11 out of the last 11 calls to <function recreate_function.<locals>.restored_function_body at 0x7f3b76874ae8> triggered tf.function retracing

### ISSUE THREAD

**Issue by awadalaa** [tensorflow/hub#734]
I encounter a Warning line several times when calling `hub.load`. The issue is exacerbated when using hub.load with Tensorflow Transform. Here is [a notebook to reproduce](https://colab.research.google.com/drive/1JZG1dkYfPEhntqNUTmVy7nwHgzqOfnB0) the issue.

The warnings line looks like this:

`WARNING:tensorflow:11 out of the last 11 calls to <function recreate_function.<locals>.restored_function_body at 0x7f3b76874ae8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.`

Using these TF versions:
```
tensorflow==2.3.2
tensorflow_transform==0.26.0
tensorflow-hub==0.11.0
```

Is there a way to resolve this warning?

**Comment by arghyaganguly** [comment]
I've tried suppressing triggered tf.function retracing warning using :- 

```
import os
os.environment['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
```

the warnings got suppressed for  function preprocessing_fn but still receiving it for run_tft_pipeline()

**Comment by arnoegw** [comment]
Sorry for the noise!

Please ignore this warning when it refers to `recreate_function.<locals>.restored_function_body`: such a tf.function is backed by a restored SavedModel and it is not actually retraced, so there is no concern.

This has been fixed in TensorFlow on the master branch by commit https://github.com/tensorflow/tensorflow/commit/3a158a0b4af1d4350d6155cca3b5357c36d71926 already in December, which will become part of the TF2.5 release in April (or so).

**Comment by arnoegw** [comment]
Sorry for the noise!

Please ignore this warning when it refers to `recreate_function.<locals>.restored_function_body`: such a tf.function is backed by a restored SavedModel and it is not actually retraced, so there is no concern.

This has been fixed in TensorFlow on the master branch by commit https://github.com/tensorflow/tensorflow/commit/3a158a0b4af1d4350d6155cca3b5357c36d71926 already in December, which will become part of the TF2.5 release in April (or so).
