### ISSUE TITLE
Correct range of input values for MobileNetV3

### ISSUE THREAD

**Issue by ogreyesp** [tensorflow/hub#739]
Hello,

I want to use the implementation of MobileNetV3 (either the MobileNet_large or MobileNet_small version) in my project. I'm using the TensorFlow v2.4.1.

 I get confused when I read the documentation about the range of input values for MobileNet-based models. According to this [link](https://tfhub.dev/google/imagenet/mobilenet_v3_large_100_224/classification/5)  the expected range of values for the model is [0,1]. However, according to this other [link](https://www.tensorflow.org/tutorials/images/transfer_learning), the correct range of values is [-1, 1]. A similar issue was already reported at this [link](https://github.com/tensorflow/hub/issues/637).

On the other hand, to my surprise, the function preprocess_input of the module [MobileNetV3](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/applications/mobilenet_v3.py#L556-L558) does not apply any change over the input; i.e. the function is returning directly the input.

```
@keras_export('keras.applications.mobilenet_v3.preprocess_input')
def preprocess_input(x, data_format=None):  # pylint: disable=unused-argument
  return x

```

So, what should be the correct range of input values for MobileNetV3?

**Comment by MorganR** [comment]
As originally written and described in its research paper, the MobileNet V3 model uses inputs in the range [-1,1]. However, whenever we upload image models to Hub, we try to follow some [common image input conventions](https://www.tensorflow.org/hub/common_signatures/images#input). This includes providing inputs in the range [0,1]. Providing a common convention makes it easy to try different models for your use-case by only changing a single line (i.e. the URL of the model to load). 

The [preprocess_input](https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet_v3/preprocess_input) function you point to is specifically intended for use with the `tf.keras.applications.MobileNetV3*` functions. If you're using the MobileNet V3 model from Hub, then you do not need to call this function. You just need to follow the common image input conventions as described above.

I hope that helps! Feel free to ask further questions if something is still unclear, otherwise please close this issue if your question has been answered.

**Comment by arghyaganguly** [comment]
@ogreyesp ,please confirm on the above comment by @MorganR.
Thanks.

**Comment by ogreyesp** [comment]
Hi,

Thank you for your response.
