### ISSUE TITLE
Feature request: specify vocab file when load preprocessor layer

### ISSUE THREAD

**Issue by HarborZeng** [tensorflow/hub#743]
Usually we just use tf_hub to load the pre-trained model and the corresponding preprocess layer(tokenize and calc position encoding and etc.) like:

```python
def build_classifier_model():
    preprocessor = hub.load(
        "https://tfhub.dev/tensorflow/bert_zh_preprocess/3")

    # Step 1: tokenize batches of text inputs.
    text_inputs = [tf.keras.layers.Input(shape=(), dtype=tf.string)]
    tokenize = hub.KerasLayer(preprocessor.tokenize)
    tokenized_inputs = [tokenize(segment) for segment in text_inputs]

    seq_length = 64
    bert_pack_inputs = hub.KerasLayer(
        preprocessor.bert_pack_inputs,
        arguments=dict(seq_length=seq_length))
    encoder_inputs = bert_pack_inputs(tokenized_inputs)


    encoder = hub.KerasLayer(
        "https://tfhub.dev/tensorflow/bert_zh_L-12_H-768_A-12/3",
        trainable=True,
        name="BERT_encoder")
    outputs = encoder(encoder_inputs)
    net = outputs['pooled_output']
    net = keras.layers.Dropout(0.1)(net)
    net = keras.layers.Dense(1, activation='sigmoid', name='classifier')(net)
    return keras.Model(text_inputs, net)
```

But what if I want to use another version of bert model like <https://github.com/brightmart/albert_zh>, so I have to change the vocab file for `preprocessor`, or write the preprocessing outside the model defination, which is not best practice for latter tensor serving deployment.

So I request a new feature for [preprocessor](https://tfhub.dev/tensorflow/bert_zh_preprocess/3) to customize vocab file path.

**Comment by akhorlin** [comment]
The tokenisation model you are looking for can be created using [TF-NLP tools](https://github.com/tensorflow/models/blob/master/official/nlp/docs/tfhub.md#exporting-the-preprocessing-model). Alternatively, TF-NLP tools can be used directly to perform tokenisation.

In general passing vocab as an arguments is challenging given semantics TF's SavedModel format. The vocab file has to be used for initialisation by StaticLookupTable. This would lead to an error-prone stateful interface in which loading the SavedModel creates the StaticLookupTable resource, the user would have to call a special initialiser function with the vocab, and only then can normal calls be made. For some tokenisers, like SentencepieceTokenizer, this approach won't work at all, because it embeds the SentencePieceModel as a node attribute within the GraphDef.

**Comment by HarborZeng** [comment]
Got it!
