### ISSUE TITLE
Please add the source distribution to PyPI

### ISSUE THREAD

**Issue by ocefpaf** [tensorflow/hub#75]
I notice that there is only a wheel available on  PyPI:

https://pypi.org/project/tensorflow-hub/#files

It would be nice to get the source distribution too.

**Comment by andresusanopinto** [comment]
IIUC source distributions are not suitable for tensorflow-hub package since the source code needs to be compile via blaze so that the proto files get converted into .py files.

Source code use to build the pipy releases are anyhow marked on the github repo:
 https://github.com/tensorflow/hub/releases
