### ISSUE TITLE
add new data

### ISSUE THREAD

**Issue by BisoDevil** [tensorflow/hub#779]
I just used this code and worked fine,
my question how can I add more images to the trained model 
example 
I trained my model with these classes 
- dog
- cat
- horse 
so how can I add just new class ex: rat

**Comment by maringeo** [comment]
Hi @BisoDevil, can you provide more details about what code you ran (for example a code snippet).

**Comment by BisoDevil** [comment]
sorry if you didn't understand me, but it's not an issue I just need to add more data to my trained model 
it's called fine tunning as I read 

I used terminal to train my model with 2 animal types after its finishes and the model works great I need to add one more animal to the trained model so at final I have three animals to test the model so I tried to add just one folder contains images for this animal but what I found is that the trained model remove the previous animal and keep only the last one 

sorry I'm new to machine learning

**Comment by maringeo** [comment]
It sounds like you're using TF Hub's `make_image_classifier` tool (https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier). If this is the case, then note that all class directories need to be on the same level, for example:
```
images_dir
|-- cat
|   |-- image1.jpg
|   |-- image2.jpg
|   `-- ...
|-- dog
|   |-- image1.jpg
|   |-- image2.jpg
|   `-- ...
`-- rabbit 
|   |-- image1.jpg
|   |-- image2.jpg
|   `-- ...
```
One way to verify whether the model is trained on the expected classes is to inspect the `make_image_classifier` command log of this line: https://github.com/tensorflow/hub/blob/master/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py#L408

**Comment by BisoDevil** [comment]
I did that and all data saved correctly my question is how to add more data 
assume if I wanna add 
"Rat animal to the trained file " so my directory will 

images_dir
|-- rat
|   |-- image1.jpg
|   |-- image2.jpg
|   `-- ...

so the lable.txt will contain only Rat class without the old data
cat,rabbit etc

> It sounds like you're using TF Hub's `make_image_classifier` tool (https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier). If this is the case, then note that all class directories need to be on the same level, for example:
> 
> ```
> images_dir
> |-- cat
> |   |-- image1.jpg
> |   |-- image2.jpg
> |   `-- ...
> |-- dog
> |   |-- image1.jpg
> |   |-- image2.jpg
> |   `-- ...
> `-- rabbit 
> |   |-- image1.jpg
> |   |-- image2.jpg
> |   `-- ...
> ```
> 
> One way to verify whether the model is trained on the expected classes is to inspect the `make_image_classifier` command log of this line: https://github.com/tensorflow/hub/blob/master/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py#L408

**Comment by maringeo** [comment]
Thank you for the clarification! 

If I understand correctly you are doing the following:
1. you train a model using `make_image_classifier` on 3 classes (for example cat, dog and rabbit)
2. you then use the model from step 1. as pre-trained model in `make_image_classifier` to fine-tune on some other animal class

Your expectation is that the model generated in step 2. will be able to classify all 4 types of animals. This expectation is not correct - I'll try to explain why.

If you look at how the Keras model is built ([this Colab](https://www.tensorflow.org/tutorials/images/transfer_learning_with_hub) is a simplified version of the make_image_classifier tool and demonstrates the exact same example) it appends two more layers after the pretrained model: https://github.com/tensorflow/hub/blob/master/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py#L298-L306. 

The last layer:
```
tf.keras.layers.Dense(
          num_classes,
          activation="softmax",
          kernel_regularizer=tf.keras.regularizers.l1_l2(
              l1=hparams.l1_regularizer, l2=hparams.l2_regularizer))
```
is what maps an intermediate representation of an image to its predicted class. This explains why when your train data contains only 1 class, then the classifier model is only able to predict one class, even if the pretrained model was trained on hundreds of classes. Note that especially for classifier tasks, in order for models to be reusable (i.e. useful for fine-tunning, transfer-learning), the last classification layer is rarely exported ([this blog is a good introduction to this topic](https://towardsdatascience.com/deep-learning-and-transfer-learning-31c6394b10c5)).

If you want to train a classifier on 4 classes, instead of training on 3 classes and trying to add an additional class afterwards, why don't you train the classifier on 4 classes from the start?

**Comment by BisoDevil** [comment]
Thank you very much for clarification. 
The reason is I will use this tool tain new class when user upload new data so I will no have all class at first time it will be added later

**Comment by maringeo** [comment]
One approach would be to retrain the model on all classes once new data is available, and then deploy the the newly trained model to production if it has good-enough performance ([TFX](https://www.tensorflow.org/tfx) might help here).

I'm closing this issue as the behaviour of `make_image_classifier` is correct. Please open another issue if you run into any problems with TF Hub.
