### ISSUE TITLE
Feature idea - int Tensors with space delimiter

### ISSUE THREAD

**Issue by georgesterpu** [tensorflow/hub#8]
Hi,
It would be very nice to have a text embedding model to accept a batch of int Tensors as inputs, instead of plain strings, with each value representing a character. The only restriction would be that the ints must correspond to the same character indices in the alphabet used to train the model (e.g. \<space\>=0, a=1, b=2, ..., \<zero_pad_value\> = 42), so that the words can be recognised and segmented properly.

Unless this is too soon :baby_chick: 
Thanks a lot for this project.

**Comment by andresusanopinto** [comment]
Hi,

It was intentional that the published text modules followed a [common signature](https://www.tensorflow.org/hub/common_signatures/text) of batch of strings in, batch of fixed dimension vector out. This interface leans toward minimizing the knowledge needed to apply a module while giving enough freedom for users and publishers of modules.

Please note that:
 - It is possible to create a mapping from batch of string to a sparse batch of chars and then use a table lookup to convert to ints. E.g. Using the empty delimiter in `tf.string_split(sentences, delimiter='')` + `tf.contrib.lookup.index_table_from_tensor`. So you could easily build that inside a module and never require the module users to know such mapping details.

 - It is also possible to create modules that accept sparse tensors of dtype=int as inputs. But such an interface would likely be harder to use than the current interface.

Thanks for the feedback and let us know if there is something else blocking you.

**Comment by georgesterpu** [comment]
Hi André, thank you very much for the explanations.

I wouldn't mind using a complex interface, if that suits better an use case which is not covered by the current one. And one example is when the strings are not available offline, but generated within the session. Is there an easy  way of doing the reverse operation you described at the first item - int tensor to string tensor ?
