### ISSUE TITLE
movenet incorrect output on RTX 3090

### ISSUE THREAD

**Issue by aafaqin** [tensorflow/hub#804]
models are giving incorrect output only on the rtx 3090.
Also the time required is also very large sometimes 10X more than RTX 2070.
Exact same code, cuda, python packages.

**Comment by yuhuichen1015** [comment]
Thanks for reporting this. To better help us understand the issue, could you:

1) Try the [tf.js demo](https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=movenet) and let us know if you see weird behavior on two different devices. This should help us double check whether the issue is for TfLite only or across different model formats.

2) Could you share more detail about the "incorrect output"? Does it give purely noise? or very biased keypoint locations? An example image would help a lot.

3) Could you share how you run the model? Which TfLite GPU delegate? Tensorflow version? Thanks!

**Comment by aafaqin** [comment]
![Screenshot from 2021-09-02 15-06-50](https://user-images.githubusercontent.com/22724087/131820843-4d777494-9b96-4e62-9ab5-0277f59ecd12.png)
This is the incorrect output i get. but when i switch to CPU only The output is totally fine. I have used the driver code given in demo
![Screenshot from 2021-09-02 15-09-18](https://user-images.githubusercontent.com/22724087/131821361-08d3ed61-1b63-46d7-9271-72cbe5c7c526.png)

**Comment by aafaqin** [comment]
I Have tried with TF 2.4 and 2.5 both python 3.9 running on RTX 3090 only its incorrect other GPUs it is running fine

**Comment by yuhuichen1015** [comment]
Thanks for sharing the information. It seems like it is a very device specific issue which we cannot easily reproduce and debug it.. we've consulted internal experts on it but no obvious thought here. Will keep you posted if we figure out how to solve it. Thanks.
