### ISSUE TITLE
Question: How can I skip loading the pretrained weights? 

### ISSUE THREAD

**Issue by hyang0129** [tensorflow/hub#871]
### What happened?

So I can load the model with the pretrained weights, but what if I want to load it without the pretrained weights? I want to return just the model structure, uninitialized preferably, and then load my own weights into it using model.load_weights. 

### Relevant code

```python
bit_model_url = "https://tfhub.dev/google/bit/s-r101x1/1"
model = hub.KerasLayer(bit_model_url)
model.load_weights('temp.h5')
```

### Relevant log output

```shell
bit_model_url = "https://tfhub.dev/google/bit/s-r101x1/1"
model = hub.KerasLayer(bit_model_url)
model.load_weights('temp.h5')
```

### tensorflow_hub Version

0.12.0 (latest stable release)

### TensorFlow Version

2.8 (latest stable release)

### Python Version

3.x

### OS

Linux

**Comment by akhorlin** [comment]
Currently there is no support for loading model structure without loading the pretrained weights. The underlying mechanism for loading models in hub.KerasLayer and hub.load comes from the core TF library, so it may make sense to raise the question of whether any work-around exists for tf.saved_model.load() on the TF repo.

**Comment by gaikwadrahul8** [comment]
Hi, @hyang0129 

As @akhorlin mentioned above we don't have an option to load pre-trained model without pre-trained weights and biases because all TF Hub models are pre-trained models and there will be pre-trained weights and biases with it so if you're looking to build your model with own model layers and want to train it, you can do it with the help of [Keras API](https://www.tensorflow.org/guide/keras/sequential_model) and you'll have to set `trainable` parameter to `True` in `hub.KerasLayer()` like below in that only pre-trained model parameters won't be trained and only newly added model layers parameters will be trained and you can save that entire model can be saved in two different file formats (SavedModel and HDF5) and to restore model weights you can use `model.load_weights()` you can refer our [official documentation](https://www.tensorflow.org/tutorials/keras/save_and_load) and [article](https://shravan-c.medium.com/transfer-learning-with-tensorflow-hub-29a4bbff8879) about Transfer Learning with Tensorflow Hub :

```
model = hub.KerasLayer(bit_model_url, input_shape=[],
                           dtype=tf.string, trainable=True)
```

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? 

If you have any further questions or need any further assistance, please let us know ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @hyang0129 

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update

Thank you!
