### ISSUE TITLE
Bug: Error loading bird-vocalization-classifier/3

### ISSUE THREAD

**Issue by lagunabravo** [tensorflow/hub#890]
### What happened?

Trying to load the upgraded bird-vocalization-classifier/3 gives an error on hub.load. 
There is no such error with previous version bird-vocalization-classifier/2

### Relevant code

```python
import tensorflow_hub as hub
model = hub.load('https://tfhub.dev/google/bird-vocalization-classifier/3')
```

### Relevant log output

```shell
FileNotFoundError: Op type not registered 'DisableCopyOnRead' in binary running on XXX. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.
```

### tensorflow_hub Version

other (please specify)

### TensorFlow Version

other (please specify)

### Other libraries

tensorflow_hub Version 0.8.0
TensorFlow Version 2.6.0

### Python Version

3.x

### OS

Windows

**Comment by singhniraj08** [comment]
@lagunabravo,

I tried importing the "bird-vocalization-classifier/3" model and was able to do it successfully. Please refer screenshot. 
The error you are receiving might be because of older versions of Tensorflow and TF-Hub installed. Please update the packages to latest version and let us know if the issue persists. Thank you!

![image](https://github.com/tensorflow/hub/assets/110809167/b62439e0-e650-4d97-8a23-59c49cc2ddfc)

**Comment by lagunabravo** [comment]
Thank you, an update to the latest packages (not so easy in windows) resolved it

**Comment by singhniraj08** [comment]
@lagunabravo, Requesting you to close this issue if you problem is resolved. Thank you!

**Comment by lagunabravo** [comment]
Sorry
